
export const  ADD_TO_TOTAL_COST= 'ADD_TO_TOTAL_COST';
export const  DELETE_OF_TOTAL_COST = 'DELETE_OF_TOTAL_COST';
export const   ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const   ACTUALIZE_CART = 'ACTUALIZE_CART';
export const   DELETE_PRODUCT_OF_CART ='DELETE_PRODUCT_OF_CART';
export const  EMPTY_CART ='EMPTY_CART';
export const  RESET_TOTAL_COST ='RESET_TOTAL_COST';
export const  TOGGLE_CART ='TOGGLE_CART';
